autorun:
  block: false
formatter:
  - clippy: {}
tools:
  bandit:
    ignore:
      - any-other-function-with-shell-equals-true
      - assert-used
      - hardcoded-bind-all-interfaces
      - hardcoded-password-default
      - hardcoded-password-funcarg
      - hardcoded-password-string
      - hardcoded-sql-expressions
      - hardcoded-tmp-directory
      - import-lxml
      - import-pickle
      - import-subprocess
      - import-xml-expat
      - import-xml-minidom
      - import-xml-pulldom
      - import-xml-sax
      - import_xml-etree
      - md5
      - random
      - start-process-with-no-shell
      - start-process-with-partial-path
      - subprocess-without-shell-equals-true
      - try-except-continue
      - urllib-urlopen
    run: true
  dlint:
    ignore: []
    run: true
  eslint:
    ignore:
      - "@typescript-eslint/camelcase"
      - "@typescript-eslint/member-delimiter-style"
      - accessor-pairs
      - array-bracket-newline
      - array-bracket-spacing
      - array-element-newline
      - arrow-body-style
      - arrow-parens
      - block-spacing
      - brace-style
      - camelcase
      - capitalized-comments
      - class-methods-use-this
      - comma-dangle
      - comma-spacing
      - comma-style
      - computed-property-spacing
      - consistent-return
      - consistent-this
      - curly
      - dot-location
      - dot-notation
      - eol-last
      - func-call-spacing
      - func-name-matching
      - func-names
      - func-style
      - function-call-argument-newline
      - function-paren-newline
      - guard-for-in
      - id-blacklist
      - id-length
      - id-match
      - implicit-arrow-linebreak
      - import/dynamic-import-chunkname
      - import/exports-last
      - import/extensions
      - import/first
      - import/group-exports
      - import/max-dependencies
      - import/newline-after-import
      - import/no-anonymous-default-export
      - import/no-cycle
      - import/no-default-export
      - import/no-duplicates
      - import/no-named-default
      - import/no-named-export
      - import/no-namespace
      - import/no-unassigned-import
      - import/order
      - import/prefer-default-export
      - indent
      - jsx-a11y/alt-text
      - jsx-a11y/anchor-has-content
      - jsx-a11y/aria-activedescendant-has-tabindex
      - jsx-a11y/click-events-have-key-events
      - jsx-a11y/html-has-lang
      - jsx-a11y/iframe-has-title
      - jsx-a11y/img-redundant-alt
      - jsx-a11y/interactive-supports-focus
      - jsx-a11y/label-has-associated-control
      - jsx-a11y/media-has-caption
      - jsx-a11y/mouse-events-have-key-events
      - jsx-a11y/no-access-key
      - jsx-a11y/no-autofocus
      - jsx-a11y/no-distracting-elements
      - jsx-a11y/no-noninteractive-element-interactions
      - jsx-a11y/no-noninteractive-tabindex
      - jsx-a11y/no-onchange
      - jsx-a11y/no-redundant-roles
      - jsx-a11y/no-static-element-interactions
      - jsx-a11y/scope
      - jsx-a11y/tabindex-no-positive
      - jsx-quotes
      - key-spacing
      - keyword-spacing
      - line-comment-position
      - linebreak-style
      - lines-around-comment
      - lines-around-directive
      - lines-between-class-members
      - max-classes-per-file
      - max-depth
      - max-len
      - max-lines
      - max-lines-per-function
      - max-nested-callbacks
      - max-params
      - max-statements
      - max-statements-per-line
      - multiline-comment-style
      - multiline-ternary
      - new-cap
      - new-parens
      - newline-per-chained-call
      - no-array-constructor
      - no-bitwise
      - no-case-declarations
      - no-cond-assign
      - no-console
      - no-continue
      - no-div-regex
      - no-else-return
      - no-empty-function
      - no-fallthrough
      - no-floating-decimal
      - no-implicit-globals
      - no-inline-comments
      - no-invalid-this
      - no-labels
      - no-lonely-if
      - no-mixed-operators
      - no-mixed-spaces-and-tabs
      - no-multi-assign
      - no-multi-spaces
      - no-multi-str
      - no-multiple-empty-lines
      - no-negated-condition
      - no-nested-ternary
      - no-new-object
      - no-octal
      - no-param-reassign
      - no-plusplus
      - no-redeclare
      - no-restricted-syntax
      - no-return-assign
      - no-script-url
      - no-self-assign
      - no-self-compare
      - no-tabs
      - no-ternary
      - no-throw-literal
      - no-trailing-spaces
      - no-underscore-dangle
      - no-unneeded-ternary
      - no-unused-vars
      - no-var
      - no-void
      - no-whitespace-before-property
      - nonblock-statement-body-position
      - object-curly-newline
      - object-curly-spacing
      - object-property-newline
      - one-var
      - one-var-declaration-per-line
      - operator-assignment
      - operator-linebreak
      - padded-blocks
      - padding-line-between-statements
      - prefer-arrow-callback
      - prefer-const
      - prefer-destructuring
      - prefer-named-capture-group
      - prefer-numeric-literals
      - prefer-object-spread
      - prefer-promise-reject-errors
      - prefer-reflect
      - prefer-rest-params
      - prefer-spread
      - prefer-template
      - quote-props
      - quotes
      - react/boolean-prop-naming
      - react/button-has-type
      - react/default-props-match-prop-types
      - react/destructuring-assignment
      - react/display-name
      - react/forbid-component-props
      - react/forbid-dom-props
      - react/forbid-elements
      - react/forbid-foreign-prop-types
      - react/forbid-prop-types
      - react/jsx-boolean-value
      - react/jsx-closing-bracket-location
      - react/jsx-closing-tag-location
      - react/jsx-curly-brace-presence
      - react/jsx-curly-newline
      - react/jsx-curly-spacing
      - react/jsx-equals-spacing
      - react/jsx-filename-extension
      - react/jsx-fragments
      - react/jsx-handler-names
      - react/jsx-indent
      - react/jsx-indent-props
      - react/jsx-key
      - react/jsx-max-depth
      - react/jsx-max-props-per-line
      - react/jsx-no-literals
      - react/jsx-one-expression-per-line
      - react/jsx-pascal-case
      - react/jsx-props-no-multi-spaces
      - react/jsx-props-no-spreading
      - react/jsx-sort-default-props
      - react/jsx-sort-prop-types
      - react/jsx-sort-props
      - react/jsx-space-before-closing
      - react/jsx-tag-spacing
      - react/jsx-wrap-multilines
      - react/no-children-prop
      - react/no-find-dom-node
      - react/no-multi-comp
      - react/no-redundant-should-component-update
      - react/no-set-state
      - react/no-string-refs
      - react/no-unknown-property
      - react/prefer-es6-class
      - react/prefer-read-only-props
      - react/prefer-stateless-function
      - react/prop-types
      - react/react-in-jsx-scope
      - react/require-default-props
      - react/require-optimization
      - react/self-closing-comp
      - react/sort-comp
      - react/sort-prop-types
      - react/state-in-constructor
      - react/static-property-placement
      - react/style-prop-object
      - semi
      - semi-spacing
      - semi-style
      - sort-keys
      - sort-vars
      - space-before-blocks
      - space-before-function-paren
      - space-in-parens
      - space-infix-ops
      - space-unary-ops
      - spaced-comment
      - strict
      - switch-colon-spacing
      - template-tag-spacing
      - unicode-bom
      - vars-on-top
      - wrap-regex
      - yoda
    run: false
  flake8:
    ignore:
      - bad-wildcard-import
      - bare-except-bugbear
      - no-getattr
      - no-setattr
      - unused-loop-variable
      - unused-module
      - unused-variable
    run: true
  gosec:
    ignore: []
    run: false
  hadolint:
    ignore:
      - DL3008
      - DL3010
      - DL3012
      - DL3018
      - DL3020
      - DL3022
      - DL3027
      - DL4001
    run: true
  r2c.boto3:
    ignore: []
    run: true
  r2c.flask:
    ignore: []
    run: true
  r2c.requests:
    ignore:
      - use-timeout
    run: true
  r2c.click:
    ignore:
      - names-are-well-formed
    run: true
  r2c.jinja:
    ignore:
      - parse-error
      - recursion-error
      - missing-meta-charset
      - missing-meta-content-type
    run: true
  shellcheck:
    ignore:
      - SC1004
      - SC1008
      - SC1009
      - SC1047
      - SC1050
      - SC1062
      - SC1071
      - SC1072
      - SC1090
      - SC1091
      - SC1105
      - SC1107
      - SC1123
      - SC1124
      - SC1126
      - SC2001
      - SC2002
      - SC2003
      - SC2004
      - SC2005
      - SC2006
      - SC2007
      - SC2009
      - SC2034
      - SC2035
      - SC2039
      - SC2155
      - SC2164
      - SC2181
      - SC2186
      - SC2196
      - SC2197
      - SC2230
    run: true
